spring.application.name=primer-parcial


spring.datasource.url=jdbc:postgresql://localhost:5432/db_primerparcial
spring.datasource.username=postgres

spring.datasource.password=2301


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
server.port=8081