spring.application.name=primer-parcial

# Conexión a tu Postgres local
spring.datasource.url=jdbc:postgresql://localhost:5432/db_primerparcial
spring.datasource.username=postgres
# Cambia esto por tu contraseña real
spring.datasource.password=2301

# Crea las tablas automáticamente basado en tus clases Java
spring.jpa.hibernate.ddl-auto=update
# Muestra el SQL en consola para auditar
spring.jpa.show-sql=true